name: Build

on:
  release:
    types:
      - published

jobs:
  backend-docker:
    name: Build backend Docker image.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1.1.0
        with:
          username: MrFlynn
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: docker.pkg.github.com/mrflynn/voyager/backend
          tag_with_ref: true
          tags: latest
  web-docker:
    name: Build web Docker image.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1.1.0
        with:
          username: MrFlynn
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          path: web/
          repository: docker.pkg.github.com/mrflynn/voyager/web
          tag_with_ref: true
          tags: latest
